server:
  port: 8081

spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:h2:mem:warehousedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
  packages-to-scan: com.vhre.warehouse_service
  model-converters:
    deprecating-converter:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/